name: Release CI

on:
  push:
    tags:
      - 'v[0-9]+'

jobs:
  make-changelog:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set Release Name
        run: echo "RELEASE_NAME=$(echo ${{ github.ref }} | sed 's#refs/tags/##')" >> $GITHUB_ENV
      
      - name: Get Last Release Tag
        id: last_tag
        run: echo "LAST_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Get Release Date
        id: release_date
        run: echo "RELEASE_DATE=$(git show -s --format=%ci ${{ env.RELEASE_NAME }})" >> $GITHUB_ENV

      - name: Install auto-changelog
        run: npm install -g auto-changelog

      - name: Generate Changelog
        run: auto-changelog --output CHANGELOG.md --starting-version ${{ env.LAST_TAG }}

      - name: Read Changelog
        id: read_changelog
        run: echo "::set-output name=changelog::$(cat CHANGELOG.md)"
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_NAME }}
          name: ${{ env.RELEASE_NAME }}
          body: |
            This is the release ${{ env.RELEASE_NAME }}.
            Changelog:
            $(cat CHANGELOG.md)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: tests for output
        run: echo "${{ env.RELEASE_DATE }}"
      
      - name: Create Release Comment
        id: create_or_update_comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.MAKE_PR_PAT }}
          issue-number: ${{ steps.find_existing_issue.outputs.issue_number }}
          body: |
            ## Release Information

            **Version:** ${{ env.RELEASE_NAME }}
            **Release Date:** ${{ env.RELEASE_DATE }}
            **Author:** ${{ github.actor }}
            **Changelog:**

            ${{ steps.read_changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME: ${{ env.RELEASE_NAME }}
          RELEASE_DATE: ${{ env.RELEASE_DATE }}